local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Warrior-Fury','Warrior-Arms','Priest-Holy','Unknown-Unknown','Rogue-Outlaw','Rogue-Assassination','Monk-Mistweaver','Warlock-Destruction','Monk-Brewmaster','Druid-Restoration','Hunter-BeastMastery','Hunter-Marksmanship','Shaman-Restoration','Shaman-Elemental','Monk-Windwalker','Warrior-Protection','DemonHunter-Havoc','Priest-Shadow','Paladin-Protection','DeathKnight-Blood','Druid-Balance','DeathKnight-Frost','Mage-Frost','Mage-Arcane','Mage-Fire','Warlock-Demonology','Druid-Feral','Druid-Guardian','Evoker-Devastation','Warlock-Affliction','Paladin-Holy','Shaman-Enhancement','Paladin-Retribution',}; local provider = {region='US',realm='Stormrage',name='US',type='subscribers',zone=44,date='2025-08-29',data={Ab='Abg:BAEALAAECgEIAQAAAA==.',Ae='Aeondale:BAECLAAFFIEKAAMBAAUIbB9rAAD8AQU5DAAAAwBjADsMAAACAF0AOgwAAAMAUQA8DAAAAQAtAD0MAAABAFIAAQAFCC4fawAA/AEFOQwAAAMAYwA7DAAAAgBdADoMAAACAE4APAwAAAEALQA9DAAAAQBSAAIAAQjlHyUBAGEAAToMAAABAFEALAAECoEWAAMBAAgInSapAACBAwABAAgInCapAACBAwACAAEIpSarEAByAAAAAA==.',Ai='Aiedarann:BAEALAAECgMIAwABLAAFFAUICgABAGwfAA==.Airllines:BAEALAAFFAEIAQAAAA==.Aisllin:BAEBLAAECoEWAAIDAAgIVySMAQA/Awg5DAAAAwBRADsMAAADAGIAOgwAAAMAYQA8DAAAAwBPADIMAAADAGMAPQwAAAMAYgA+DAAAAgBiAD8MAAACAFsAAwAICFckjAEAPwMIOQwAAAMAUQA7DAAAAwBiADoMAAADAGEAPAwAAAMATwAyDAAAAwBjAD0MAAADAGIAPgwAAAIAYgA/DAAAAgBbAAEsAAUUAQgBAAQAAAAA.',Ak='Akkaryn:BAEALAADCggICAAAAA==.',Al='Aldrimord:BAEALAAECgMIAwAAAA==.Allundead:BAEALAAECggIEQAAAA==.Alvanys:BAEALAAECggICAAAAA==.Alvyrage:BAEALAADCgcIBwABLAAECggICAAEAAAAAA==.Alynnara:BAEBLAAECoEWAAMFAAgI6huNAQCiAgg5DAAAAwBYADsMAAADAEMAOgwAAAMAXQA8DAAAAwA1ADIMAAADAFAAPQwAAAMAWQA+DAAAAgAvAD8MAAACADMABQAICOobjQEAogIIOQwAAAIAWAA7DAAAAgBDADoMAAACAF0APAwAAAIANQAyDAAAAwBQAD0MAAADAFkAPgwAAAIALwA/DAAAAgAzAAYABAgeCdsuANcABDkMAAABACAAOwwAAAEAIgA6DAAAAQAOADwMAAABAAwAAAA=.',Ap='Apoccalypse:BAEALAAFFAIIAgAAAA==.',As='Ashelune:BAEALAAECgEIAQABLAAECgcIDgAEAAAAAA==.Ashjik:BAEALAAECgcIDgAAAA==.Askaori:BAECLAAFFIEOAAIHAAYI1hgXAAA+AgY5DAAAAwA0ADsMAAADAF4AOgwAAAMAPwA8DAAAAgA/ADIMAAABAEQAPQwAAAIAJgAHAAYI1hgXAAA+AgY5DAAAAwA0ADsMAAADAF4AOgwAAAMAPwA8DAAAAgA/ADIMAAABAEQAPQwAAAIAJgAsAAQKgRkAAgcACAgXIVIDAM0CAAcACAgXIVIDAM0CAAAA.Asmiev:BAEALAAECgMIAwABLAAFFAYIDgAHANYYAA==.',At='Atemae:BAEALAAECgcIBwAAAA==.Atemu:BAEALAAECgIIAgABLAAECgcIBwAEAAAAAA==.Attierius:BAEALAAFFAEIAQAAAA==.',Au='Audiolight:BAEALAAECgcIDAAAAA==.Auslöschen:BAEBLAAECoEVAAIIAAgILB5iCQC1Agg5DAAAAwBJADsMAAADAEgAOgwAAAIAYAA8DAAAAwBUADIMAAADAFEAPQwAAAMAWwA+DAAAAwBXAD8MAAABAB4ACAAICCweYgkAtQIIOQwAAAMASQA7DAAAAwBIADoMAAACAGAAPAwAAAMAVAAyDAAAAwBRAD0MAAADAFsAPgwAAAMAVwA/DAAAAQAeAAAA.',Ba='Babyrager:BAECLAAFFIEJAAIJAAQImCKXAACVAQQ5DAAAAwBfADsMAAACAFQAOgwAAAMAYAA9DAAAAQBNAAkABAiYIpcAAJUBBDkMAAADAF8AOwwAAAIAVAA6DAAAAwBgAD0MAAABAE0ALAAECoEWAAIJAAgIfCZ2AAB4AwAJAAgIfCZ2AAB4AwABLAAFFAEIAQAEAAAAAA==.',Be='Beam:BAEALAADCggICAABLAAFFAMIBAAEAAAAAA==.Beiqi:BAEALAAECgYIEwAAAA==.Bestgoatgirl:BAEALAAECggICAAAAA==.Bestvoidgirl:BAEBLAAECoEUAAMFAAcIjyJiAQC5Agc5DAAAAwBVADsMAAADAF8AOgwAAAMAUwA8DAAAAwBYADIMAAADAFsAPQwAAAMAWAA+DAAAAgBWAAUABwiPImIBALkCBzkMAAACAFUAOwwAAAIAXwA6DAAAAwBTADwMAAADAFgAMgwAAAMAWwA9DAAAAwBYAD4MAAACAFYABgACCHINETsAcwACOQwAAAEAFwA7DAAAAQAtAAEsAAQKCAgIAAQAAAAA.',Bi='Bigshifty:BAEALAAECgcIEQAAAA==.',Bl='Blackflare:BAEALAADCggIFwAAAA==.',Bo='Boodybear:BAEBLAAECoEZAAIKAAgIuhtBCQBiAgg5DAAABABLADsMAAAEAFwAOgwAAAQAUQA8DAAAAgAvADIMAAADAD8APQwAAAMAVgA+DAAAAwBCAD8MAAACADUACgAICLobQQkAYgIIOQwAAAQASwA7DAAABABcADoMAAAEAFEAPAwAAAIALwAyDAAAAwA/AD0MAAADAFYAPgwAAAMAQgA/DAAAAgA1AAAA.Boodywaves:BAEALAAECgYICwABLAAECggIGQAKALobAA==.Borovoidin:BAEALAAECgUIBgAAAA==.',Br='Brandon:BAEALAAFFAMIBAAAAQ==.Breezyxd:BAEALAAECgYICQAAAA==.Brivdruid:BAEALAAECggIBwAAAA==.Brivp:BAEALAAECgYIEQABLAAECggIBwAEAAAAAA==.Bronzkewicz:BAEALAAECgcIEQAAAA==.',Bu='Butlickr:BAEALAADCgYIBgABLAAECgIIAgAEAAAAAA==.',['Bú']='Búll:BAEALAAECggICwAAAA==.',Ca='Cavorkath:BAEALAAECgYIDAAAAA==.',Ch='Chainoncds:BAEALAADCgcIBwABLAAFFAEIAQAEAAAAAA==.Cheedoz:BAEALAAECggIBgAAAA==.Cheery:BAECLAAFFIEFAAMLAAMIYxwfAQAtAQM5DAAAAgBjADsMAAABAEoAOgwAAAIAKwALAAMIYxwfAQAtAQM5DAAAAgBjADsMAAABAEoAOgwAAAEAKwAMAAEIaQVoCgBBAAE6DAAAAQANACwABAqBGAACCwAICIck7gIAQAMACwAICIck7gIAQAMAAAA=.Cheeryoh:BAEALAAECgIIAgABLAAFFAMIBQALAGMcAA==.Cherle:BAEALAAECgYIDAAAAA==.Chipotlea:BAEBLAAECoEXAAMNAAgICR/yCACBAgg5DAAAAwBMADsMAAADAGAAOgwAAAMAPgA8DAAAAwBNADIMAAADAFoAPQwAAAMAUwA+DAAAAwBbAD8MAAACADgADQAICAkf8ggAgQIIOQwAAAIATAA7DAAAAgBgADoMAAACAD4APAwAAAIATQAyDAAAAgBaAD0MAAACAFMAPgwAAAIAWwA/DAAAAgA4AA4ABwhmDswfAKUBBzkMAAABAAkAOwwAAAEANAA6DAAAAQAqADwMAAABACkAMgwAAAEAIQA9DAAAAQAlAD4MAAABACgAAAA=.Chipotlei:BAEALAADCgcICwABLAAECggIFwANAAkfAA==.Chipotlel:BAEALAADCgcIDQABLAAECggIFwANAAkfAA==.Chunkfumasta:BAEALAAECgYICQAAAA==.',Co='Coggali:BAEALAAECgYICAAAAA==.Coldreality:BAEALAADCgcIBwABLAAFFAIIAgAEAAAAAA==.',Cr='Craengus:BAEBLAAECoEWAAIPAAgIvxE4CwACAgg5DAAABAAxADsMAAAEAFEAOgwAAAQAKAA8DAAABAArADIMAAACACgAPQwAAAIAOwA+DAAAAQAWAD8MAAABABgADwAICL8ROAsAAgIIOQwAAAQAMQA7DAAABABRADoMAAAEACgAPAwAAAQAKwAyDAAAAgAoAD0MAAACADsAPgwAAAEAFgA/DAAAAQAYAAAA.Crapet:BAEALAAECgcICgABLAAFFAMIBgAQAN8iAA==.Cryomuffin:BAEALAADCggICAAAAA==.',Da='Daemonjin:BAEALAAECgcIDwAAAA==.Dallargee:BAEALAAFFAIIAgABLAAFFAMIAwAEAAAAAA==.Dallmoon:BAEALAAFFAMIAwAAAA==.Danburns:BAEALAADCggICAABLAAFFAMIBQARADYWAA==.Darkknive:BAEALAAECgMIAwAAAA==.Dawlish:BAEALAAFFAIIAgAAAA==.',De='Defarus:BAECLAAFFIEFAAIRAAMINhYiAwASAQM5DAAAAgBFADsMAAABACsAOgwAAAIAOQARAAMINhYiAwASAQM5DAAAAgBFADsMAAABACsAOgwAAAIAOQAsAAQKgRcAAhEACAjlI2wCAF8DABEACAjlI2wCAF8DAAAA.Deliverancé:BAEALAADCgcICgABLAAECgQIBwAEAAAAAA==.Delkrieg:BAEALAAECgQIBwAAAA==.Delusionol:BAEBLAAECoEeAAMDAAgIQyHuFAAIAgg5DAAABQBhADsMAAAFAE4AOgwAAAUAWAA8DAAABABbADIMAAAEAF0APQwAAAQASwA+DAAAAgBSAD8MAAABAEoAAwAGCE0g7hQACAIGOQwAAAMAYQA7DAAAAwBOADoMAAADAFgAPQwAAAIASwA+DAAAAgBSAD8MAAABAEoAEgAGCDcb4RoAxgEGOQwAAAIAWAA7DAAAAgBQADoMAAACACkAPAwAAAQALwAyDAAABABUAD0MAAACAEsAAAA=.Demontegual:BAEALAAECgYICQAAAA==.Destoresto:BAEALAAECgMIBAABLAAECggIFwALALsaAA==.Destoshot:BAEBLAAECoEXAAILAAgIuxp/DQCOAgg5DAAAAwBaADsMAAADAFcAOgwAAAMAXgA8DAAAAwBFADIMAAADADcAPQwAAAMALAA+DAAAAwA1AD8MAAACADQACwAICLsafw0AjgIIOQwAAAMAWgA7DAAAAwBXADoMAAADAF4APAwAAAMARQAyDAAAAwA3AD0MAAADACwAPgwAAAMANQA/DAAAAgA0AAAA.Deuuky:BAEALAAFFAIIAgAAAA==.',Dr='Draggionn:BAEALAAECgQIBAAAAA==.Draxfur:BAEALAAECgEIAQAAAA==.Drinkkus:BAEALAAECgMIAwABLAAFFAUICgATAHgRAA==.Drutile:BAECLAAFFIEOAAIFAAYIniABAABgAgY5DAAAAwBkADsMAAADAGQAOgwAAAMAZAA8DAAAAgBkADIMAAABAAAAPQwAAAIAZAAFAAYIniABAABgAgY5DAAAAwBkADsMAAADAGQAOgwAAAMAZAA8DAAAAgBkADIMAAABAAAAPQwAAAIAZAAsAAQKgR4AAgUACAjlJH4AAC4DAAUACAjlJH4AAC4DAAAA.',Du='Dudly:BAEALAAECggIDwABLAAFFAMIBQATAC4ZAA==.',Dw='Dwarfdotname:BAEALAADCgcIBwABLAAECggIGAATADwhAA==.',Ec='Eclip:BAEALAADCgcIBwABLAAECgEIAQAEAAAAAA==.Ecovoker:BAEALAAECgIIBAAAAA==.',El='Elemen:BAEALAAECgEIAQABLAAECgYICAAEAAAAAA==.',Er='Eritiya:BAEALAAECggIEAAAAA==.',Ev='Everville:BAEALAAECgMIAwAAAA==.Evynne:BAEALAAECggIAQAAAA==.',Fe='Feral:BAEALAADCgcIBwABLAAFFAUICgAUANwSAA==.',Fi='Figg:BAEBLAAECoEXAAISAAgIzR9QBwDeAgg5DAAAAwBZADsMAAADAF8AOgwAAAMAVAA8DAAAAwBGADIMAAADAFgAPQwAAAMAYQA+DAAAAwBWAD8MAAACACYAEgAICM0fUAcA3gIIOQwAAAMAWQA7DAAAAwBfADoMAAADAFQAPAwAAAMARgAyDAAAAwBYAD0MAAADAGEAPgwAAAMAVgA/DAAAAgAmAAAA.',Fo='Foxiestorm:BAEALAADCggICAABLAAECgYIFAARAJoUAA==.Foxiez:BAEBLAAECoEUAAIRAAYImhSKMQCWAQY5DAAABgBIADsMAAAEADMAOgwAAAQARAA8DAAAAgAwADIMAAACACEAPQwAAAIAKAARAAYImhSKMQCWAQY5DAAABgBIADsMAAAEADMAOgwAAAQARAA8DAAAAgAwADIMAAACACEAPQwAAAIAKAAAAA==.',Fr='Friarbacon:BAEALAAECgYICgAAAA==.Friardragon:BAEALAADCggICAABLAAECgYICgAEAAAAAA==.Fridayoclock:BAEBLAAECoEYAAIVAAgIhR8HCQChAgg5DAAABABFADsMAAADAFgAOgwAAAMAVAA8DAAAAwBMADIMAAADAFMAPQwAAAMAYgA+DAAAAgBKAD8MAAADAEYAFQAICIUfBwkAoQIIOQwAAAQARQA7DAAAAwBYADoMAAADAFQAPAwAAAMATAAyDAAAAwBTAD0MAAADAGIAPgwAAAIASgA/DAAAAwBGAAAA.',Fu='Fujikan:BAEALAAECgIIAgAAAA==.',Ga='Gabriellá:BAEALAAECgMIBAABLAAECgQIBgAEAAAAAA==.',Ge='Gerosdrk:BAEALAAFFAEIAQAAAA==.',Gl='Glider:BAEALAADCgIIAgABLAAFFAMIBgAQAN8iAA==.Glitcheddrud:BAEALAAECggIAQABLAAFFAIIAgAEAAAAAA==.Glitchedmonk:BAEALAAFFAIIAgAAAA==.Gloomstorm:BAEALAADCgcIBwABLAAECggICAAEAAAAAA==.Gloomwick:BAEALAAECggICAAAAA==.',Go='Gordiie:BAEBLAAECoEYAAIWAAgIXiaUAACCAwg5DAAAAwBjADsMAAADAGMAOgwAAAMAYgA8DAAAAwBjADIMAAADAGEAPQwAAAMAYwA+DAAAAwBhAD8MAAADAF8AFgAICF4mlAAAggMIOQwAAAMAYwA7DAAAAwBjADoMAAADAGIAPAwAAAMAYwAyDAAAAwBhAD0MAAADAGMAPgwAAAMAYQA/DAAAAwBfAAAA.',Gr='Gregmâge:BAEBLAAECoEXAAIXAAgIQSQOAQBPAwg5DAAAAwBhADsMAAADAGIAOgwAAAMAYgA8DAAAAwBhADIMAAADAGMAPQwAAAMAYwA+DAAAAwBiAD8MAAACADQAFwAICEEkDgEATwMIOQwAAAMAYQA7DAAAAwBiADoMAAADAGIAPAwAAAMAYQAyDAAAAwBjAD0MAAADAGMAPgwAAAMAYgA/DAAAAgA0AAAA.Grudshade:BAEALAAECggIDQABLAAFFAIIAgAEAAAAAA==.',Gu='Guildmaster:BAECLAAFFIEKAAIUAAUI3BJJAACuAQU5DAAAAwBIADsMAAACACcAOgwAAAMATAA8DAAAAQAhAD0MAAABABMAFAAFCNwSSQAArgEFOQwAAAMASAA7DAAAAgAnADoMAAADAEwAPAwAAAEAIQA9DAAAAQATACwABAqBFAACFAAICHwldgEAMAMAFAAICHwldgEAMAMAAAA=.Guvk:BAEALAAECgEIAQAAAA==.',Ho='Holyscooty:BAEALAAECgcICgAAAA==.Hoodblinks:BAEALAAECgcIDQABLAAFFAMIBQAYAC8dAA==.Hoodyblinky:BAECLAAFFIEFAAIYAAMILx0PAwAhAQM5DAAAAgBdADsMAAABACoAOgwAAAIAWAAYAAMILx0PAwAhAQM5DAAAAgBdADsMAAABACoAOgwAAAIAWAAsAAQKgRgAAxgACAikJTgFACMDABgACAjEJDgFACMDABkAAgiGIe4GALUAAAAA.',Hu='Huevonphobia:BAEALAAECgYIBgAAAA==.Hugehotter:BAEALAADCgcICAABLAAECgcIDQAEAAAAAA==.Hunterkilla:BAEALAAECgEIAQAAAA==.',Ic='Icedracthyr:BAEALAADCgcIBwABLAAECggIDwAEAAAAAA==.Icemonkey:BAEALAAECggIDwAAAA==.',Il='Illp:BAEALAAECgYICAAAAA==.',Im='Imfknstupid:BAEALAAECgEIAQABLAAECgcIDQAEAAAAAA==.',Je='Jearrisey:BAEALAAECgMIBQAAAA==.',Ju='Judgen:BAECLAAFFIEFAAIDAAMI/BsRAgAaAQM5DAAAAgBDADsMAAABAEQAOgwAAAIATwADAAMI/BsRAgAaAQM5DAAAAgBDADsMAAABAEQAOgwAAAIATwAsAAQKgRcAAwMACAiWHhUIAKkCAAMACAiWHhUIAKkCABIAAgjnAu5DAGgAAAAA.Junkxd:BAEALAAECggIEAABLAAECgYICAAEAAAAAA==.',['Jö']='Jöss:BAEALAAECgYIDAAAAA==.',Ka='Kaisuxhehe:BAEALAAECgEIAQABLAAECggIGwACAPckAA==.Kaisuxlol:BAEBLAAECoEbAAMCAAgI9yREAABVAwg5DAAABABjADsMAAADAGMAOgwAAAQAYwA8DAAAAwBjADIMAAADAGMAPQwAAAQAYwA+DAAAAwBTAD8MAAADAEsAAgAICPckRAAAVQMIOQwAAAMAYwA7DAAAAgBjADoMAAADAGMAPAwAAAIAYwAyDAAAAgBjAD0MAAADAGMAPgwAAAEAUwA/DAAAAQBLAAEACAjbGjYVAB0CCDkMAAABAFYAOwwAAAEAUAA6DAAAAQA5ADwMAAABADkAMgwAAAEAUQA9DAAAAQAxAD4MAAACAEEAPwwAAAIASQAAAA==.Kanegasi:BAEALAAECgMIBAAAAA==.Kaíyo:BAEALAAECgYICgAAAA==.',Ke='Kegsmashed:BAEALAAFFAIIAgAAAA==.',Kh='Khavina:BAEALAAECggIEwAAAA==.Khaxzar:BAEALAAFFAEIAQAAAA==.',Ki='Killadeathjr:BAEALAADCggIEAABLAAECgEIAQAEAAAAAA==.Kiviana:BAEALAAECgYIBgABLAAECgcIFAAaAPoaAA==.Kivilocks:BAEALAAECgcIDQABLAAECgcIFAAaAPoaAA==.Kivø:BAEALAAECgYIBgABLAAECgcIFAAaAPoaAA==.',Ko='Komosky:BAEALAAECgIIAgAAAA==.',Ky='Kyñrine:BAEALAADCggICAAAAA==.',Le='Leafmunchr:BAEBLAAECoEWAAQbAAgIqxflCADfAQg5DAAAAwBHADsMAAADAGAAOgwAAAMAPgA8DAAAAwAuADIMAAADAEEAPQwAAAMATgA+DAAAAgAbAD8MAAACACMAGwAGCHIb5QgA3wEGOQwAAAIARwA7DAAAAgBgADoMAAABAD4APAwAAAEALgAyDAAAAQBBAD0MAAACAE4ACgAHCCcTGB0AggEHOQwAAAEAJgA7DAAAAQBFADoMAAABADYAPAwAAAEAJAAyDAAAAQBHAD4MAAACABsAPwwAAAIALAAcAAQIYwcICwC8AAQ6DAAAAQATADwMAAABAA0AMgwAAAEABAA9DAAAAQAmAAAA.Levence:BAEALAADCggIDwAAAA==.Levimbro:BAEALAAECgUICAAAAA==.',Li='Libzd:BAEALAAECgIIAgABLAAECggIIQAdAHkfAA==.Libzvoker:BAEBLAAECoEhAAIdAAgIeR/HAwAOAwg5DAAABQBhADsMAAAFAF4AOgwAAAUAVwA8DAAABgBhADIMAAAEAFUAPQwAAAMAYQA+DAAAAwAxAD8MAAACACIAHQAICHkfxwMADgMIOQwAAAUAYQA7DAAABQBeADoMAAAFAFcAPAwAAAYAYQAyDAAABABVAD0MAAADAGEAPgwAAAMAMQA/DAAAAgAiAAAA.Lilpost:BAEALAAFFAIIAgAAAA==.Listhuh:BAEALAADCgMIAwABLAAECggIGAATADwhAA==.',Lo='Lothem:BAECLAAFFIEFAAITAAMILhn6AAD+AAM5DAAAAgBTADsMAAABABgAOgwAAAIAVAATAAMILhn6AAD+AAM5DAAAAgBTADsMAAABABgAOgwAAAIAVAAsAAQKgRwAAhMACAgLJn4AAHUDABMACAgLJn4AAHUDAAAA.',Lu='Luneli:BAEALAAECgQIBwABLAAECgcIFAAaAPoaAA==.Lunilocks:BAEBLAAECoEUAAQaAAcI+hqHEACCAQc5DAAAAwBXADsMAAADAFoAOgwAAAMAOgA8DAAAAwBEADIMAAADADkAPQwAAAMARwA+DAAAAgAvABoABgi1G4cQAIIBBjkMAAACAFcAOwwAAAMAWgA6DAAAAwA6ADwMAAADAEQAPQwAAAMARwA+DAAAAgAvAAgAAgjmGQRJAI4AAjkMAAABAEoAMgwAAAIAOQAeAAEI4AiZKQBIAAEyDAAAAQAWAAAA.',Ma='Madauntie:BAEALAAECgIIAgAAAA==.Madkel:BAEALAADCgcIBwABLAAECgIIAgAEAAAAAA==.Madkelli:BAEALAADCgcIBwABLAAECgIIAgAEAAAAAA==.Madkely:BAEALAAECgIIAgABLAAECgIIAgAEAAAAAA==.Malthadorbs:BAEBLAAECoEXAAIbAAgIGyOsAABHAwg5DAAAAwBiADsMAAADAGAAOgwAAAMAYQA8DAAAAwBgADIMAAADADAAPQwAAAMAXwA+DAAAAwBbAD8MAAACAF4AGwAICBsjrAAARwMIOQwAAAMAYgA7DAAAAwBgADoMAAADAGEAPAwAAAMAYAAyDAAAAwAwAD0MAAADAF8APgwAAAMAWwA/DAAAAgBeAAAA.Mannafhuil:BAEALAAECgUICwAAAA==.',Mi='Mibrax:BAEALAAECgcIEQAAAA==.Mikethepure:BAEALAAECgYIBgAAAA==.Mistytome:BAEBLAAECoEYAAIHAAgI+hePBwA/Agg5DAAAAwAxADsMAAAEAFAAOgwAAAQAVgA8DAAAAwBEADIMAAADAFMAPQwAAAMAIwA+DAAAAgA0AD8MAAACACIABwAICPoXjwcAPwIIOQwAAAMAMQA7DAAABABQADoMAAAEAFYAPAwAAAMARAAyDAAAAwBTAD0MAAADACMAPgwAAAIANAA/DAAAAgAiAAAA.Mithràndîr:BAEBLAAECoEWAAIYAAgIDB1uFgBeAgg5DAAAAwBaADsMAAADAFYAOgwAAAMAUgA8DAAAAwBWADIMAAADAFQAPQwAAAMASQA+DAAAAgA/AD8MAAACABsAGAAICAwdbhYAXgIIOQwAAAMAWgA7DAAAAwBWADoMAAADAFIAPAwAAAMAVgAyDAAAAwBUAD0MAAADAEkAPgwAAAIAPwA/DAAAAgAbAAAA.',Mo='Moff:BAEALAADCgEIAQABLAADCgYIBgAEAAAAAA==.Momodh:BAEBLAAECoEWAAIRAAgI2yRyAwBMAwg5DAAAAwBjADsMAAADAGMAOgwAAAMAYAA8DAAAAwBfADIMAAADAGMAPQwAAAMAYwA+DAAAAgBRAD8MAAACAFMAEQAICNskcgMATAMIOQwAAAMAYwA7DAAAAwBjADoMAAADAGAAPAwAAAMAXwAyDAAAAwBjAD0MAAADAGMAPgwAAAIAUQA/DAAAAgBTAAAA.Moonblase:BAEALAADCgUIBQABLAAECggIDwAEAAAAAA==.',['Mô']='Môffvariant:BAEALAADCgYIBgAAAA==.',Na='Nahuall:BAEALAADCggIDQAAAA==.Nancydrewíd:BAEALAAECggIDgABLAAECgQIBAAEAAAAAA==.Nawrp:BAEALAADCggICAABLAAECgYICAAEAAAAAA==.Nazzynaz:BAEALAAECgYIBwAAAA==.',Ne='Neepz:BAEALAAECgEIAQAAAA==.',Ni='Nireyn:BAEALAAECgcIDQAAAA==.',Nr='Nrobsethas:BAECLAAFFIEFAAISAAMIViODAQBAAQM5DAAAAgBhADsMAAABAFoAOgwAAAIAUwASAAMIViODAQBAAQM5DAAAAgBhADsMAAABAFoAOgwAAAIAUwAsAAQKgRYAAhIACAjFJaYBAFwDABIACAjFJaYBAFwDAAAA.',Ny='Nynaevy:BAEALAAECgMIBAABLAAECgcIEQAEAAAAAA==.',Oa='Oakfang:BAEALAAECgcIDgAAAA==.',Pa='Pandice:BAECLAAFFIEFAAIYAAIIkQ9DDQCfAAI5DAAAAwA1ADoMAAACABoAGAACCJEPQw0AnwACOQwAAAMANQA6DAAAAgAaACwABAqBKAACGAAICJgibgcABwMAGAAICJgibgcABwMAASwAAwoCCAIABAAAAAA=.',Pe='Pebballs:BAEBLAAECoEUAAIRAAgIqSW8AQBuAwg5DAAAAgBjADsMAAADAGQAOgwAAAIAYwA8DAAAAwBiADIMAAADAGMAPQwAAAMAYwA+DAAAAgBjAD8MAAACAEsAEQAICKklvAEAbgMIOQwAAAIAYwA7DAAAAwBkADoMAAACAGMAPAwAAAMAYgAyDAAAAwBjAD0MAAADAGMAPgwAAAIAYwA/DAAAAgBLAAAA.Pebbalt:BAEALAAECggIDgABLAAECggIFAARAKklAA==.Pengadin:BAEBLAAECoEYAAIfAAgIswnlEgCrAQg5DAAAAwA8ADsMAAADABUAOgwAAAMAFAA8DAAAAwACADIMAAADACAAPQwAAAMAGAA+DAAAAwARAD8MAAADABMAHwAICLMJ5RIAqwEIOQwAAAMAPAA7DAAAAwAVADoMAAADABQAPAwAAAMAAgAyDAAAAwAgAD0MAAADABgAPgwAAAMAEQA/DAAAAwATAAAA.',Pg='Pgchi:BAEBLAAECoEWAAIPAAgIah8KBADXAgg5DAAAAwBSADsMAAADAFgAOgwAAAMAWgA8DAAAAwBWADIMAAADAFoAPQwAAAMASAA+DAAAAgAtAD8MAAACAFYADwAICGofCgQA1wIIOQwAAAMAUgA7DAAAAwBYADoMAAADAFoAPAwAAAMAVgAyDAAAAwBaAD0MAAADAEgAPgwAAAIALQA/DAAAAgBWAAAA.',Pi='Pigson:BAEALAAECgUIBgAAAA==.',Pl='Plexyn:BAEALAAECgYIBgAAAA==.',Po='Pocketzzmage:BAEALAADCgIIAgABLAAECggIFwAHABQbAA==.Pocketzzmonk:BAEBLAAECoEXAAIHAAgIFBu/BQB2Agg5DAAAAwBQADsMAAADAFwAOgwAAAMAPgA8DAAAAwA5ADIMAAADAFoAPQwAAAMAPwA+DAAAAwBRAD8MAAACABsABwAICBQbvwUAdgIIOQwAAAMAUAA7DAAAAwBcADoMAAADAD4APAwAAAMAOQAyDAAAAwBaAD0MAAADAD8APgwAAAMAUQA/DAAAAgAbAAAA.Podromortis:BAEALAADCgcIFAAAAA==.Popularmagus:BAEALAAECgMIAwAAAA==.Powwfu:BAEALAADCgIIAgAAAA==.',Pr='Prinkkus:BAECLAAFFIEKAAITAAUIeBFKAACNAQU5DAAAAwBWADsMAAACACoAOgwAAAMASgA8DAAAAQALAD0MAAABAAgAEwAFCHgRSgAAjQEFOQwAAAMAVgA7DAAAAgAqADoMAAADAEoAPAwAAAEACwA9DAAAAQAIACwABAqBGQACEwAICJEkKAEARwMAEwAICJEkKAEARwMAAAA=.',Pu='Punchymoose:BAEALAAECgYIDQAAAA==.',Ra='Rathòrd:BAEALAAECgYIDAAAAA==.',Re='Reddy:BAEALAAECgYIDAAAAA==.Redsy:BAEALAADCggICwABLAAECgYIDAAEAAAAAA==.Rehobooam:BAEALAADCggIEAAAAA==.Repeatable:BAEALAAFFAEIAQAAAA==.',Ro='Roles:BAEALAADCggICAABLAAFFAUICgAUANwSAA==.',Ru='Rugur:BAEALAADCggICAABLAAECggICAAEAAAAAA==.',Sa='Sabinor:BAEALAADCggIDwABLAAECgYICwAEAAAAAA==.Saebinor:BAEALAADCggIFQABLAAECgYICwAEAAAAAA==.Saffron:BAEALAADCgcICQABLAAECgYICQAEAAAAAA==.Sagamage:BAEALAAECgYICgAAAA==.Sahjurn:BAEALAAECgIIAgABLAAECggIDwAEAAAAAA==.Saurohnn:BAEALAADCggIFwAAAA==.Savory:BAEALAAECgYICQAAAA==.',Sc='Screamkus:BAEALAAECgYIDAABLAAFFAUICgATAHgRAA==.',Se='Settek:BAECLAAFFIEGAAIQAAMI3yLsAAAuAQM5DAAAAgBfADsMAAACAF4AOgwAAAIATgAQAAMI3yLsAAAuAQM5DAAAAgBfADsMAAACAF4AOgwAAAIATgAsAAQKgRgAAhAACAgfJoYAAHYDABAACAgfJoYAAHYDAAAA.',Sg='Sgeridan:BAEALAAECgYICAAAAA==.',Sh='Shiftacey:BAEALAAECgYICQAAAA==.Shiftyashe:BAEALAAECgIIAgAAAA==.',Sk='Skyraia:BAEALAADCggIBwAAAA==.',Sl='Slicerz:BAEALAADCgcIBwABLAAECgEIAQAEAAAAAA==.',So='Solastera:BAEALAADCgUIBQABLAAECgYICgAEAAAAAA==.Sostrong:BAEALAADCggICAABLAAFFAMIAwAEAAAAAA==.Sostronkforu:BAEALAADCggIEAABLAAFFAMIAwAEAAAAAA==.Sozia:BAEALAAECgMIAwABLAAFFAUICgABAGwfAA==.',Sp='Sparkyooboom:BAEALAADCgYIBgABLAAECgQIBAAEAAAAAA==.',Sq='Sqzx:BAEALAAECgYIDgAAAA==.',St='Staskyfel:BAEBLAAECoEXAAIRAAgIwCFECAD8Agg5DAAAAwBhADsMAAADAGIAOgwAAAMATQA8DAAAAwBbADIMAAADAFQAPQwAAAMAXAA+DAAAAwBCAD8MAAACAFMAEQAICMAhRAgA/AIIOQwAAAMAYQA7DAAAAwBiADoMAAADAE0APAwAAAMAWwAyDAAAAwBUAD0MAAADAFwAPgwAAAMAQgA/DAAAAgBTAAAA.Stonetdragon:BAEBLAAECoEiAAILAAgIgx0/CgC9Agg5DAAABgBZADsMAAAGAF4AOgwAAAUAVAA8DAAABgBVADIMAAAEAEMAPQwAAAQAWAA+DAAAAgAvAD8MAAABAC8ACwAICIMdPwoAvQIIOQwAAAYAWQA7DAAABgBeADoMAAAFAFQAPAwAAAYAVQAyDAAABABDAD0MAAAEAFgAPgwAAAIALwA/DAAAAQAvAAAA.Stonetides:BAEBLAAECoEXAAIgAAgIWyO3AAA1Awg5DAAAAwBcADsMAAADAGIAOgwAAAMATQA8DAAAAwBcADIMAAADAF8APQwAAAMAXQA+DAAAAwBkAD8MAAACAEgAIAAICFsjtwAANQMIOQwAAAMAXAA7DAAAAwBiADoMAAADAE0APAwAAAMAXAAyDAAAAwBfAD0MAAADAF0APgwAAAMAZAA/DAAAAgBIAAAA.Ströng:BAEALAAFFAMIAwAAAA==.',Su='Sulfurcheese:BAEALAADCggICAAAAA==.',Ta='Taboner:BAEALAAECgYICAAAAA==.Tallgeesee:BAEALAADCggICAABLAAECggIFwAhAPMiAA==.',Th='Thaw:BAEALAADCgQIBAABLAAFFAMIBgAQAN8iAA==.Theldrassen:BAEALAAECgYICgAAAA==.',To='Tomestrider:BAEALAAECgEIAQABLAAECggIGAAHAPoXAA==.Torjack:BAEALAAECggIEwAAAA==.Toströng:BAEALAADCggIGAABLAAFFAMIAwAEAAAAAA==.',Tr='Trovyria:BAEALAAECgcIDgAAAA==.',Ty='Tyromezz:BAEBLAAECoEYAAITAAgIPCHgAgDcAgg5DAAAAwBcADsMAAADAFwAOgwAAAMAVAA8DAAAAwBVADIMAAADAEYAPQwAAAMAYAA+DAAAAwBLAD8MAAADAFMAEwAICDwh4AIA3AIIOQwAAAMAXAA7DAAAAwBcADoMAAADAFQAPAwAAAMAVQAyDAAAAwBGAD0MAAADAGAAPgwAAAMASwA/DAAAAwBTAAAA.',Ul='Ullp:BAEALAADCgUIBQABLAAECgYICAAEAAAAAA==.',Uw='Uwutyro:BAEALAADCggICAABLAAECggIGAATADwhAA==.',Va='Vaelishh:BAEALAAECgQIBgAAAA==.Vayeatee:BAEBLAAECoEXAAIhAAgI8yIHBQAxAwg5DAAAAwBZADsMAAADAFYAOgwAAAMAVgA8DAAAAwBeADIMAAADAF8APQwAAAMAXgA+DAAAAwBaAD8MAAACAE0AIQAICPMiBwUAMQMIOQwAAAMAWQA7DAAAAwBWADoMAAADAFYAPAwAAAMAXgAyDAAAAwBfAD0MAAADAF4APgwAAAMAWgA/DAAAAgBNAAAA.',Vi='Violent:BAEALAAECgYIDAAAAA==.',We='Weakaura:BAEALAAECgIIAgABLAAFFAUICgAUANwSAA==.',Wh='Whitebloom:BAEALAADCgcIBQABLAADCggIFwAEAAAAAA==.',Wi='Windowblight:BAEALAAECggIEQAAAA==.',Wr='Wraîth:BAEALAAECgYICAAAAA==.',Xa='Xalafort:BAEBLAAECoEWAAISAAgIpyNxAwAxAwg5DAAAAwBiADsMAAADAGEAOgwAAAMAXQA8DAAAAwBLADIMAAADAF0APQwAAAMAYgA+DAAAAgBWAD8MAAACAFUAEgAICKcjcQMAMQMIOQwAAAMAYgA7DAAAAwBhADoMAAADAF0APAwAAAMASwAyDAAAAwBdAD0MAAADAGIAPgwAAAIAVgA/DAAAAgBVAAAA.',Ya='Yabiss:BAEALAADCgcIDQABLAADCggIEAAEAAAAAA==.Yamoneta:BAEALAAECgYIDAAAAA==.Yartadin:BAEALAADCgcIBwABLAAECgMIBgAEAAAAAA==.Yartb:BAEALAAECgMIAwABLAAECgMIBgAEAAAAAA==.Yartlock:BAEALAAECgMIBgAAAA==.Yartmm:BAEALAADCgEIAQABLAAECgMIBgAEAAAAAA==.',Yl='Yliara:BAEALAAECggIDgAAAA==.',Yo='Yokofel:BAEALAAECgYICgAAAA==.',Yu='Yusukeurames:BAEALAADCggICAABLAAECggIFwAhAPMiAA==.',Yv='Yvairel:BAEALAAECggIDwABLAAFFAMIBQAOAL8VAA==.',Za='Zagzy:BAEALAAECgMIAwAAAQ==.',Zg='Zgzz:BAEBLAAECoEUAAISAAgIrxlIDACAAgg5DAAABABbADsMAAADAFUAOgwAAAMANgA8DAAAAgAlADIMAAACAFgAPQwAAAIAWgA+DAAAAgAdAD8MAAACADEAEgAICK8ZSAwAgAIIOQwAAAQAWwA7DAAAAwBVADoMAAADADYAPAwAAAIAJQAyDAAAAgBYAD0MAAACAFoAPgwAAAIAHQA/DAAAAgAxAAEsAAQKAwgDAAQAAAAA.',['Óh']='Óh:BAEBLAAECoEXAAQIAAgIvCNSBAAaAwg5DAAAAwBeADsMAAADAFwAOgwAAAMAVgA8DAAAAwBWADIMAAADAFsAPQwAAAMAWgA+DAAAAwBfAD8MAAACAF8ACAAICLwjUgQAGgMIOQwAAAIAXgA7DAAAAgBcADoMAAABAFYAPAwAAAIAVgAyDAAAAwBbAD0MAAACAFoAPgwAAAMAXwA/DAAAAgBfAB4ABAjcFgsQADIBBDkMAAABAEcAOwwAAAEARQA6DAAAAQBHADwMAAABABUAGgACCIggETMAoQACOgwAAAEAVgA9DAAAAQBQAAAA.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end