local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
 local lookup = {'Monk-Mistweaver','Shaman-Restoration','DeathKnight-Blood','DeathKnight-Frost','Monk-Brewmaster','Evoker-Devastation','Unknown-Unknown','Warlock-Demonology','Warlock-Destruction','Paladin-Retribution','Druid-Feral','Druid-Balance','Shaman-Elemental','Rogue-Assassination','Rogue-Outlaw','Rogue-Subtlety','Warlock-Affliction','Priest-Shadow','Hunter-BeastMastery','Monk-Windwalker','Druid-Guardian','DemonHunter-Havoc','Mage-Arcane','Evoker-Preservation','Priest-Holy','Paladin-Protection','Mage-Fire','Hunter-Marksmanship','Warrior-Protection','Druid-Restoration','Warrior-Fury',}; local provider = {region='US',realm='Tichondrius',name='US',type='subscribers',zone=44,date='2025-08-29',data={Ac='Acromonkx:BAEBLAAFFIEGAAIBAAMIKB5FAQAZAQM5DAAAAgBTADsMAAACADkAOgwAAAIAWgABAAMIKB5FAQAZAQM5DAAAAgBTADsMAAACADkAOgwAAAIAWgABLAAFFAQIBgACAOcfAA==.Acrosham:BAEBLAAFFIEGAAICAAQI5x9tAACkAQQ5DAAAAgBiADoMAAACAGEAMgwAAAEAUwA9DAAAAQAvAAIABAjnH20AAKQBBDkMAAACAGIAOgwAAAIAYQAyDAAAAQBTAD0MAAABAC8AAAA=.',Ae='Aecicle:BAEBLAAECoEXAAMDAAgInB7aAgDPAgg5DAAAAwBVADsMAAADAFoAOgwAAAMAUQA8DAAAAwBMADIMAAAEAE4APQwAAAQASgA+DAAAAgBJAD8MAAABAEIAAwAICJwe2gIAzwIIOQwAAAIAVQA7DAAAAgBaADoMAAACAFEAPAwAAAIATAAyDAAAAwBOAD0MAAADAEoAPgwAAAIASQA/DAAAAQBCAAQABggCCx1PABgBBjkMAAABACUAOwwAAAEAQAA6DAAAAQAUADwMAAABABkAMgwAAAEAEgA9DAAAAQABAAEsAAUUBQgLAAUApxYA.',Al='Allo:BAEALAAECgEIAQAAAA==.Allsublime:BAECLAAFFIEIAAIGAAUIyBXUAAC+AQU5DAAAAQBAADsMAAACADIAOgwAAAMARwA8DAAAAQBKAD0MAAABABEABgAFCMgV1AAAvgEFOQwAAAEAQAA7DAAAAgAyADoMAAADAEcAPAwAAAEASgA9DAAAAQARACwABAqBFgACBgAICGEkFwMAIgMABgAICGEkFwMAIgMAAAA=.Allsubmage:BAEALAAECgYIEAABLAAFFAUICAAGAMgVAA==.',Ar='Arcanetru:BAEALAAECgMIAwABLAAECggIDgAHAAAAAA==.',As='Astralsurge:BAEALAAECgcIBgAAAA==.',Ba='Babayäga:BAECLAAFFIEFAAMIAAMIQAgmBgCdAAM5DAAAAgAoADsMAAABAAwAOgwAAAIACQAIAAII1gkmBgCdAAI5DAAAAgAoADoMAAACAAkACQABCBMF3w8ATQABOwwAAAEADAAsAAQKgRgAAwgACAh3GWkLALYBAAgACAjxFWkLALYBAAkABAjNE203AAMBAAAA.Ballthazzar:BAEBLAAECoEUAAIKAAcI7R+NGgAnAgc5DAAAAwBbADsMAAAEAGAAOgwAAAMAQgA8DAAAAwBYADIMAAADAEEAPQwAAAMAXAA+DAAAAQBGAAoABwjtH40aACcCBzkMAAADAFsAOwwAAAQAYAA6DAAAAwBCADwMAAADAFgAMgwAAAMAQQA9DAAAAwBcAD4MAAABAEYAAAA=.Ballthazzarx:BAEALAADCgcIBwABLAAECgcIFAAKAO0fAA==.',Be='Beatlegeus:BAEALAADCggICAABLAAECgYICAAHAAAAAA==.Bendiesel:BAEBLAAFFIELAAIFAAUIpxaEAACxAQU5DAAAAwA/ADsMAAACADwAOgwAAAMASgA8DAAAAgBHAD0MAAABABMABQAFCKcWhAAAsQEFOQwAAAMAPwA7DAAAAgA8ADoMAAADAEoAPAwAAAIARwA9DAAAAQATAAAA.',Bi='Bigbrewbies:BAEALAADCggICAAAAA==.Bigmilk:BAEBLAAECoEUAAMLAAcIZyG5AwCYAgc5DAAAAwBjADsMAAADAFQAOgwAAAMAWAA8DAAAAwBMADIMAAADAEoAPQwAAAMATgA+DAAAAgBhAAsABwhnIbkDAJgCBzkMAAABAGMAOwwAAAIAVAA6DAAAAgBYADwMAAACAEwAMgwAAAEASgA9DAAAAQBOAD4MAAABAGEADAAHCI8byxQA7wEHOQwAAAIAVwA7DAAAAQBUADoMAAABAFcAPAwAAAEAMwAyDAAAAgAvAD0MAAACAEIAPgwAAAEAQwAAAA==.Biscuitbaddy:BAEALAAECgMIAwABLAAFFAMIBQANACMgAA==.Bizzr:BAEBLAAECoEXAAQOAAgIASDZBADyAgg5DAAABABbADsMAAADAGAAOgwAAAMATwA8DAAAAwBbADIMAAADAFQAPQwAAAMAXwA+DAAAAgBAAD8MAAACADMADgAICAEg2QQA8gIIOQwAAAQAWwA7DAAAAwBgADoMAAADAE8APAwAAAMAWwAyDAAAAgBUAD0MAAADAF8APgwAAAIAQAA/DAAAAQAzAA8AAQhkFiYNAEYAATIMAAABADkAEAABCAgLdxYAQQABPwwAAAEAHAABLAAECgMIBAAHAAAAAA==.Bizzwiz:BAEALAAECgMIBAAAAA==.',Bo='Bokator:BAEALAAECgYICAAAAA==.Bonaparte:BAEALAAECgMIAwAAAA==.Bovinemight:BAEALAADCggICAABLAAFFAEIAQAHAAAAAA==.',Br='Bradbozo:BAEALAAECgYICQAAAA==.Brobeam:BAEALAAECgQIBgAAAA==.',Bu='Bunnygamer:BAEBLAAECoEWAAQJAAgIOiMgBwDfAgg5DAAAAgBfADsMAAADAFwAOgwAAAIASgA8DAAAAwBeADIMAAADAFkAPQwAAAMAWgA+DAAAAwBfAD8MAAADAFkACQAICDojIAcA3wIIOQwAAAIAXwA7DAAAAwBcADoMAAACAEoAPAwAAAIAXgAyDAAAAgBZAD0MAAACAFoAPgwAAAMAXwA/DAAAAwBZABEAAggQElYcAJsAAjwMAAABABYAMgwAAAEARQAIAAEIsQc8SwBAAAE9DAAAAQATAAEsAAUUBwgQAAYA7BoA.Bunní:BAECLAAFFIEFAAISAAQIKgknAgAaAQQ5DAAAAQACADsMAAACACMAOgwAAAEAKwA8DAAAAQAMABIABAgqCScCABoBBDkMAAABAAIAOwwAAAIAIwA6DAAAAQArADwMAAABAAwALAAECoEYAAISAAgIxyUmAgBQAwASAAgIxyUmAgBQAwAAAA==.Bunnï:BAEALAADCggIDAABLAAFFAQIBQASACoJAA==.',Ca='Caladari:BAEALAADCgcICAABLAADCggICAAHAAAAAA==.Calahunts:BAEALAADCggICAAAAA==.Carmuhh:BAEALAAECgYICAAAAA==.Carston:BAEALAADCgQIBAABLAAECgMIAwAHAAAAAA==.',Ch='Chidragoon:BAEALAADCgMIAwABLAAECgcIFgAMAJMUAA==.Churchill:BAEALAADCgMIBQABLAAECgMIAwAHAAAAAA==.',Da='Dalmin:BAEALAAECgQIBAABLAAECggIFwASAM0fAA==.Darkslip:BAEALAADCgEIAQAAAA==.',De='Demureonova:BAEALAAECgMIAwAAAA==.',Di='Dipsetw:BAEALAAECgcIDQAAAA==.',Do='Dougzug:BAEALAADCgMIAwABLAAFFAMIBQANACMgAA==.Downbeatx:BAEBLAAECoEYAAITAAgI9SReAwA2Awg5DAAAAwBjADsMAAADAFYAOgwAAAMAXAA8DAAAAwBhADIMAAADAGMAPQwAAAMAYgA+DAAAAwBdAD8MAAADAFgAEwAICPUkXgMANgMIOQwAAAMAYwA7DAAAAwBWADoMAAADAFwAPAwAAAMAYQAyDAAAAwBjAD0MAAADAGIAPgwAAAMAXQA/DAAAAwBYAAAA.Downbeatxo:BAEALAADCgcICAABLAAECggIGAATAPUkAA==.Downbolt:BAEALAAECgYIBgABLAAECggIGAATAPUkAA==.',Dr='Drakedekay:BAEBLAAECoEeAAIDAAgI6RcIBgAqAgg5DAAABABJADsMAAAEAEcAOgwAAAQAOwA8DAAABABBADIMAAAEADcAPQwAAAUASwA+DAAAAwA3AD8MAAACACEAAwAICOkXCAYAKgIIOQwAAAQASQA7DAAABABHADoMAAAEADsAPAwAAAQAQQAyDAAABAA3AD0MAAAFAEsAPgwAAAMANwA/DAAAAgAhAAAA.',Du='Durpn:BAEBLAAECoEYAAIUAAgIdiXPAABgAwg5DAAAAwBhADsMAAADAGEAOgwAAAMAYQA8DAAAAwBcADIMAAADAF0APQwAAAMAYAA+DAAAAwBeAD8MAAADAGEAFAAICHYlzwAAYAMIOQwAAAMAYQA7DAAAAwBhADoMAAADAGEAPAwAAAMAXAAyDAAAAwBdAD0MAAADAGAAPgwAAAMAXgA/DAAAAwBhAAAA.',Ea='Earrl:BAEBLAAECoEUAAIVAAgI7w3cBACTAQg5DAAAAwBFADsMAAADACsAOgwAAAMAGgA8DAAAAwASADIMAAADABcAPQwAAAIANgA+DAAAAgAZAD8MAAABABgAFQAICO8N3AQAkwEIOQwAAAMARQA7DAAAAwArADoMAAADABoAPAwAAAMAEgAyDAAAAwAXAD0MAAACADYAPgwAAAIAGQA/DAAAAQAYAAAA.Eavvie:BAEALAAECggICAAAAA==.',Ec='Eckszugzug:BAEALAAECgYIBgAAAA==.',En='Entru:BAEALAAECggIDgAAAA==.',Er='Ercah:BAEBLAAECoEXAAICAAgIOiG1AwDjAgg5DAAAAwBdADsMAAACAF0AOgwAAAMAUwA8DAAAAwBRADIMAAAEAE0APQwAAAQAXAA+DAAAAgBRAD8MAAACAEwAAgAICDohtQMA4wIIOQwAAAMAXQA7DAAAAgBdADoMAAADAFMAPAwAAAMAUQAyDAAABABNAD0MAAAEAFwAPgwAAAIAUQA/DAAAAgBMAAAA.Erceh:BAEALAAECgEIAQABLAAECggIFwACADohAA==.',Ev='Evilkenevill:BAEALAAFFAIIAgABLAAECgcIDQAHAAAAAA==.Evilkinevill:BAEALAAECgcIDQAAAA==.',Fi='Fiallodh:BAEBLAAECoEeAAIWAAgIBiYqAQB7Awg5DAAABABjADsMAAAEAGMAOgwAAAYAYwA8DAAABABaADIMAAAEAGIAPQwAAAMAYgA+DAAAAwBhAD8MAAACAF4AFgAICAYmKgEAewMIOQwAAAQAYwA7DAAABABjADoMAAAGAGMAPAwAAAQAWgAyDAAABABiAD0MAAADAGIAPgwAAAMAYQA/DAAAAgBeAAEsAAUUAggGABcAMBEA.Fiallohunter:BAEALAADCggICQABLAAFFAIIBgAXADARAA==.Fiallomage:BAECLAAFFIEGAAIXAAIIMBGoDACjAAI5DAAAAwAZADoMAAADAD4AFwACCDARqAwAowACOQwAAAMAGQA6DAAAAwA+ACwABAqBGAACFwAHCO0ZPTIAngEAFwAHCO0ZPTIAngEAAAA=.Fidèle:BAEALAAECgYICwAAAA==.Fishies:BAEALAADCgYIBgABLAAECggIGAAUAHYlAA==.Fistingway:BAEALAADCgcIDAABLAAECggIDAAHAAAAAA==.',Fl='Flybyz:BAECLAAFFIEHAAIYAAMIVhSwAQAHAQM5DAAAAwBGADsMAAABACcAOgwAAAMALgAYAAMIVhSwAQAHAQM5DAAAAwBGADsMAAABACcAOgwAAAMALgAsAAQKgSAAAhgACAjYIOUBANACABgACAjYIOUBANACAAAA.',Fo='Fotmbottom:BAEALAAECgYICQABLAAECgYICQAHAAAAAA==.',Fu='Fuglyfumpkin:BAEALAADCggICQABLAAECgYICQAHAAAAAA==.',['Fï']='Fïdele:BAEALAADCgUIBQABLAAECgYICwAHAAAAAA==.',Gi='Gigashocker:BAECLAAFFIEGAAINAAMIqyOpAQA1AQM5DAAAAgBhADsMAAACAFsAOgwAAAIAVQANAAMIqyOpAQA1AQM5DAAAAgBhADsMAAACAFsAOgwAAAIAVQAsAAQKgRgAAg0ACAidJZgBAGQDAA0ACAidJZgBAGQDAAAA.',Go='Golgothe:BAEALAADCggICAAAAA==.Goose:BAEALAAECgcIDQABLAAFFAUIBwASAGQOAA==.Gortadin:BAEALAAECgcIDQAAAA==.',Ha='Halnko:BAEALAAECgYIBgABLAAFFAMIBQAQAEsiAA==.',Ja='Jackmerrius:BAEBLAAECoEbAAILAAcI9yNNAgDjAgc5DAAABABfADsMAAAEAFcAOgwAAAQAVAA8DAAABQBfADIMAAAEAGIAPQwAAAMAYQA+DAAAAwBVAAsABwj3I00CAOMCBzkMAAAEAF8AOwwAAAQAVwA6DAAABABUADwMAAAFAF8AMgwAAAQAYgA9DAAAAwBhAD4MAAADAFUAAAA=.Jadefirejuri:BAEALAAECgYIBgABLAAFFAYIDQAZADAiAA==.Jalakadoom:BAEALAADCgUIBQABLAAECgMIAwAHAAAAAA==.',Ji='Jinrop:BAEALAAECggIDAAAAA==.',Ke='Keppler:BAEALAAECggICAAAAA==.',Kh='Khaotom:BAEALAAECggIAQABLAAECggIDAAHAAAAAA==.Khayame:BAEBLAAFFIENAAIZAAYIMCIEAACAAgY5DAAAAwBiADsMAAACAF0AOgwAAAMAXQA8DAAAAgBRADIMAAABAEAAPQwAAAIAXQAZAAYIMCIEAACAAgY5DAAAAwBiADsMAAACAF0AOgwAAAMAXQA8DAAAAgBRADIMAAABAEAAPQwAAAIAXQAAAA==.',Ki='Kibitokai:BAEALAAECgEIAQABLAAECggIFQAaAOoiAA==.Kidkovid:BAECLAAFFIEFAAINAAMIIyCcAQA5AQM5DAAAAgBfADsMAAABADUAOgwAAAIAYgANAAMIIyCcAQA5AQM5DAAAAgBfADsMAAABADUAOgwAAAIAYgAsAAQKgRcAAg0ACAgcJtUAAHsDAA0ACAgcJtUAAHsDAAAA.',Kn='Knocksmist:BAEBLAAFFIEFAAIBAAMIfxWoAQAEAQM5DAAAAgA0ADsMAAABACwAOgwAAAIARAABAAMIfxWoAQAEAQM5DAAAAgA0ADsMAAABACwAOgwAAAIARAAAAA==.',La='Lanî:BAEALAAECgIIAgAAAA==.Lanîa:BAEALAAECgIIBAABLAAECgIIAgAHAAAAAA==.Lanîcus:BAEALAAECgUIBQABLAAECgIIAgAHAAAAAA==.',Lh='Lhaerial:BAEALAADCgYIBgABLAAECggIDgAHAAAAAA==.',Li='Lichiexyz:BAECLAAFFIEGAAQIAAUI3BAnAgC8AAU5DAAAAQBbADsMAAACAE4AOgwAAAEAJgA8DAAAAQAFAD0MAAABAAIACAACCFQZJwIAvAACOQwAAAEAWwA6DAAAAQAmAAkAAgjMD3oIAKoAAjsMAAACAE4APQwAAAEAAgARAAEIDgJgAQBTAAE8DAAAAQAFACwABAqBGQAECAAICAMk6QMANQIACAAHCOUc6QMANQIACQAECL0i7CQAigEAEQADCDseGxEAIwEAAAA=.Lightsham:BAEALAAECgEIAQAAAA==.Lilbirch:BAEALAAECgYIDwABLAAECgYICAAHAAAAAA==.Lilgrippy:BAEALAADCggICAABLAAECgYICAAHAAAAAA==.Lilmeta:BAEALAAFFAIIAgAAAA==.Littlethorg:BAEALAADCgYICAABLAAECggIDgAHAAAAAA==.Lividity:BAEALAADCgEIAQAAAA==.',Ly='Lyeinoh:BAEALAAECgYICQAAAA==.',Ma='Machx:BAEBLAAECoEeAAINAAgIgiQCAwBDAwg5DAAABABiADsMAAAEAFkAOgwAAAQAXwA8DAAABABbADIMAAAEAGMAPQwAAAQAYQA+DAAABABZAD8MAAACAFUADQAICIIkAgMAQwMIOQwAAAQAYgA7DAAABABZADoMAAAEAF8APAwAAAQAWwAyDAAABABjAD0MAAAEAGEAPgwAAAQAWQA/DAAAAgBVAAAA.Machxr:BAEALAADCgcIBwABLAAECggIHgANAIIkAA==.',Me='Metadpsguy:BAEALAAECgcIDwAAAA==.',Mi='Mikaellewis:BAEALAAECgUIBQABLAAFFAEIAQAHAAAAAA==.Mirek:BAECLAAFFIEJAAIBAAQIRxapAABfAQQ5DAAAAwBLADsMAAACACYAOgwAAAMALQA9DAAAAQBDAAEABAhHFqkAAF8BBDkMAAADAEsAOwwAAAIAJgA6DAAAAwAtAD0MAAABAEMALAAECoEYAAIBAAgImyCEAwDFAgABAAgImyCEAwDFAgAAAA==.',Mo='Moarpunchiez:BAEALAADCgQIBAABLAAFFAIIAgAHAAAAAQ==.Moarshapez:BAEALAAECgYICwABLAAFFAIIAgAHAAAAAQ==.Moarshockz:BAEALAAECgMIBQABLAAFFAIIAgAHAAAAAQ==.Moarsoulz:BAEALAAECgEIAQABLAAFFAIIAgAHAAAAAQ==.Moartotemz:BAEALAAFFAIIAgAAAQ==.Moldymcgee:BAEALAAECgIIAgAAAA==.',Mu='Muhmmra:BAEALAAECgEIAQABLAAECgYICQAHAAAAAA==.Munkkikettu:BAEALAAECgQIBgAAAA==.Murpster:BAEALAAECgcIDgAAAA==.',Na='Nastyplot:BAEALAAECgYICAAAAA==.',Ne='Neuromonk:BAEALAAECgIIAgABLAAECgcIGwALAPcjAA==.Neuropriest:BAEALAADCgcIDQABLAAECgcIGwALAPcjAA==.',Ni='Nickspriests:BAECLAAFFIEFAAIZAAMIMhvyAQAdAQM5DAAAAgBVADsMAAABACYAOgwAAAIAVQAZAAMIMhvyAQAdAQM5DAAAAgBVADsMAAABACYAOgwAAAIAVQAsAAQKgRUAAhkACAhQIsIDAPwCABkACAhQIsIDAPwCAAAA.',No='Norrín:BAEALAAECgcIDgAAAA==.Notxyllah:BAEALAAECgcIEQABLAAECggIDAAHAAAAAA==.',Ns='Nsirp:BAEBLAAECoEXAAMXAAgImyU3AgBWAwg5DAAAAwBjADsMAAADAGMAOgwAAAMAXAA8DAAAAwBfADIMAAADAF8APQwAAAMAYwA+DAAAAwBhAD8MAAACAFsAFwAICFwlNwIAVgMIOQwAAAMAYwA7DAAAAwBjADoMAAACAFcAPAwAAAMAXwAyDAAAAgBfAD0MAAADAGMAPgwAAAMAYQA/DAAAAgBbABsAAggjImkHAKQAAjoMAAABAFwAMgwAAAEAUgAAAA==.',Nu='Nullfox:BAEALAAECgcICwAAAA==.',Nv='Nveed:BAEALAAECgcIDQAAAA==.',Ny='Nyfaria:BAEBLAAECoEVAAICAAgIoxRUHADVAQg5DAAAAwA6ADsMAAADADcAOgwAAAMATAA8DAAAAwA6ADIMAAADAC8APQwAAAMANQA+DAAAAgAvAD8MAAABABoAAgAICKMUVBwA1QEIOQwAAAMAOgA7DAAAAwA3ADoMAAADAEwAPAwAAAMAOgAyDAAAAwAvAD0MAAADADUAPgwAAAIALwA/DAAAAQAaAAAA.',['Nò']='Nòrrin:BAEALAADCgcIBwABLAAECgcIDgAHAAAAAA==.',Of='Ofelija:BAEALAADCgYIBgABLAAFFAMIBQASANIbAA==.',On='Onebtnspec:BAEALAADCgYIDwABLAAECggIDAAHAAAAAA==.',Or='Oraedaraelia:BAEALAAECgMIBQAAAA==.',Ow='Owlmovement:BAEALAAECgIIAgABLAAECgYICAAHAAAAAA==.',Pa='Pallybeau:BAEBLAAECoEVAAMaAAgI6iLeAQAeAwg5DAAAAwBUADsMAAADAF8AOgwAAAMAXwA8DAAAAwBfADIMAAADAGAAPQwAAAMAVgA+DAAAAgBeAD8MAAABAEMAGgAICLgi3gEAHgMIOQwAAAIAUAA7DAAAAwBfADoMAAADAF8APAwAAAMAXwAyDAAAAwBgAD0MAAADAFYAPgwAAAIAXgA/DAAAAQBDAAoAAQjkIGl7AFoAATkMAAABAFQAAAA=.Pandamonz:BAEALAAECgYIDAAAAA==.',Pr='Prophelija:BAECLAAFFIEFAAISAAMI0hvsAQAnAQM5DAAAAgBBADsMAAABADcAOgwAAAIAXAASAAMI0hvsAQAnAQM5DAAAAgBBADsMAAABADcAOgwAAAIAXAAsAAQKgRUAAxIACAgZJGwCAEkDABIACAgZJGwCAEkDABkABAjiCYM8ANQAAAAA.',Ra='Rainonz:BAEALAAECggIEwAAAA==.Randyorlando:BAEBLAAECoEVAAIVAAgIViGRAAAFAwg5DAAAAgBcADsMAAADAGEAOgwAAAMAXAA8DAAAAwBUADIMAAADAFsAPQwAAAMAYQA+DAAAAgBIAD8MAAACADUAFQAICFYhkQAABQMIOQwAAAIAXAA7DAAAAwBhADoMAAADAFwAPAwAAAMAVAAyDAAAAwBbAD0MAAADAGEAPgwAAAIASAA/DAAAAgA1AAAA.Rangedead:BAEALAADCgUIBQAAAA==.Rathclose:BAEALAAECgEIAQABLAAECggIFwATACchAA==.Rathproximal:BAEBLAAECoEXAAMTAAgIJyFODwB3Agg5DAAAAwBeADsMAAADAFEAOgwAAAMAPgA8DAAAAwBZADIMAAADAF0APQwAAAMAYwA+DAAAAwBgAD8MAAACAD0AEwAICMQbTg8AdwIIOQwAAAIAXgA7DAAAAgBGADoMAAACAA8APAwAAAIAVgAyDAAAAwBdAD0MAAABADQAPgwAAAIAYAA/DAAAAQA7ABwABwiBH0kLAF4CBzkMAAABAF0AOwwAAAEAUQA6DAAAAQA+ADwMAAABAFkAPQwAAAIAYwA+DAAAAQBMAD8MAAABAD0AAAA=.',Re='Reileralt:BAEALAAECgcIDQAAAA==.',Ro='Roaracle:BAEALAAECgMIAwABLAAFFAMIBQAUAHETAA==.Rokstedi:BAEALAADCgEIAQABLAAECgQIBgAHAAAAAA==.',Rv='Rvvldk:BAEALAADCgYIBgAAAA==.',Sc='Scruzz:BAECLAAFFIEFAAIQAAMISyJdAAA/AQM5DAAAAgBgADsMAAABAEYAOgwAAAIAXwAQAAMISyJdAAA/AQM5DAAAAgBgADsMAAABAEYAOgwAAAIAXwAsAAQKgRgAAhAACAjXJVkAAFMDABAACAjXJVkAAFMDAAAA.',Se='Sense:BAECLAAFFIEOAAIdAAYIYiYFAACvAgY5DAAAAwBkADsMAAADAGQAOgwAAAMAYwA8DAAAAgBkADIMAAABAFoAPQwAAAIAZAAdAAYIYiYFAACvAgY5DAAAAwBkADsMAAADAGQAOgwAAAMAYwA8DAAAAgBkADIMAAABAFoAPQwAAAIAZAAsAAQKgRgAAh0ACAj8Jg8AAKUDAB0ACAj8Jg8AAKUDAAAA.',Sk='Skwerts:BAEBLAAECoEVAAMNAAgIVCF4BQAPAwg5DAAAAwBdADsMAAADAFUAOgwAAAMAWwA8DAAAAwBaADIMAAADAFwAPQwAAAMAUAA+DAAAAgBdAD8MAAABADcADQAICFQheAUADwMIOQwAAAMAXQA7DAAAAgBVADoMAAACAFsAPAwAAAMAWgAyDAAAAwBcAD0MAAADAFAAPgwAAAIAXQA/DAAAAQA3AAIAAgjmEYtoAGgAAjsMAAABACkAOgwAAAEAMQAAAA==.Skyes:BAEBLAAECoEXAAIeAAgIBCNJAwDgAgg5DAAAAwBdADsMAAADAF0AOgwAAAMAYgA8DAAAAwBHADIMAAADAGIAPQwAAAMATwA+DAAAAwBiAD8MAAACAFMAHgAICAQjSQMA4AIIOQwAAAMAXQA7DAAAAwBdADoMAAADAGIAPAwAAAMARwAyDAAAAwBiAD0MAAADAE8APgwAAAMAYgA/DAAAAgBTAAAA.',So='Sonicslushie:BAEALAADCggIDgAAAA==.Soradruid:BAEALAAFFAIIAgAAAA==.Soulmana:BAEBLAAECoEZAAMdAAcIYxfsDQC2AQc5DAAABABDADsMAAAGAFMAOgwAAAUAMwA8DAAAAwAqADIMAAACADkAPQwAAAIAQwA+DAAAAwAxAB0ABwhjF+wNALYBBzkMAAADAEMAOwwAAAUAUwA6DAAABAAzADwMAAACACoAMgwAAAEAOQA9DAAAAQBDAD4MAAACADEAHwAHCMwDJjAAJwEHOQwAAAEAAwA7DAAAAQATADoMAAABAA8APAwAAAEABAAyDAAAAQALAD0MAAABAAQAPgwAAAEACQAAAA==.Soulmanä:BAEALAAECggICAABLAAECggIGQAdAGMXAA==.',Sp='Spargycat:BAEALAAECggIEwAAAA==.',St='Stormdragöön:BAEALAAECgYIBgABLAAECgcIFgAMAJMUAA==.',Su='Supidiot:BAEALAAECgIIAgABLAAECgYICAAHAAAAAA==.',Sv='Sveep:BAEBLAAFFIEFAAITAAIIdBmaBAC6AAI5DAAAAwBBADsMAAACAEAAEwACCHQZmgQAugACOQwAAAMAQQA7DAAAAgBAAAAA.Sveepa:BAEALAAECgcIEgABLAAFFAIIBQATAHQZAA==.Sveeptres:BAEALAADCggICAABLAAFFAIIBQATAHQZAA==.',Sw='Swayicus:BAECLAAFFIEFAAMIAAMI8SOfAADUAAM5DAAAAgBcADsMAAABAFoAOgwAAAIAXQAIAAIISCSfAADUAAI5DAAAAQBcADoMAAACAF0ACQACCDgdjQUAxQACOQwAAAEAOwA7DAAAAQBaACwABAqBFwAECQAICEglowIAQAMACQAICOwjowIAQAMACAAECL0kxA0AnAEAEQACCFIK4h4AiQAAASwABAoCCAIABwAAAAA=.Swiftsouljr:BAEALAADCggIGAAAAA==.',Ta='Taaurminator:BAEALAADCggIHAABLAAECgQIBgAHAAAAAA==.Tablepls:BAEALAAECgYIBgAAAA==.Taekel:BAEBLAAECoEUAAIYAAcIOiVbAQDzAgc5DAAAAwBYADsMAAADAF8AOgwAAAMAYQA8DAAABABhADIMAAADAGIAPQwAAAIAYgA+DAAAAgBbABgABwg6JVsBAPMCBzkMAAADAFgAOwwAAAMAXwA6DAAAAwBhADwMAAAEAGEAMgwAAAMAYgA9DAAAAgBiAD4MAAACAFsAAAA=.Tahklock:BAEBLAAECoEYAAQRAAgIbSKlAQC3Agg5DAAAAwBfADsMAAADAFYAOgwAAAMAVwA8DAAAAwBdADIMAAADAGEAPQwAAAMAXQA+DAAAAwBXAD8MAAADAD4ACQAICNshcAUAAAMIOQwAAAEAXwA7DAAAAQBWADoMAAABAFcAPAwAAAEAXQAyDAAAAQBVAD0MAAABAF0APgwAAAEAVwA/DAAAAQA+ABEACAgrGqUBALcCCDkMAAABAFIAOwwAAAEARAA6DAAAAQBXADwMAAACADwAMgwAAAIAYQA9DAAAAQA/AD4MAAABAB4APwwAAAIALgAIAAUISRlSGgA8AQU5DAAAAQBZADsMAAABAB0AOgwAAAEAQAA9DAAAAQBbAD4MAAABAC8AAAA=.',Te='Testblade:BAEALAAECgYICQABLAAFFAMIBgAXAJQUAA==.Testblink:BAECLAAFFIEGAAMXAAMIlBQ2BAAJAQM5DAAAAgAnADsMAAACABkAOgwAAAIAXQAXAAMIGxI2BAAJAQM5DAAAAQAUADsMAAACABkAOgwAAAEAXQAbAAIImxIMAQCeAAI5DAAAAQAnADoMAAABADcALAAECoEXAAMXAAgIaSC7DwCiAgAXAAgIPiC7DwCiAgAbAAIIMh4YBwCvAAAAAA==.Testdrake:BAEALAAECgQIBQABLAAFFAMIBgAXAJQUAA==.',Th='Thechad:BAEALAAECgYICQABLAAFFAIIAgAHAAAAAA==.Theprimebeef:BAEALAAECgYIBgABLAAFFAUICwAFAKcWAA==.Thesplash:BAEALAAECgYIBgABLAAFFAYIDQAZADAiAA==.Thicknscaly:BAECLAAFFIEQAAIGAAcI7BoCAADQAgc5DAAAAwBjADsMAAADAGEAOgwAAAMASgA8DAAAAgA/ADIMAAACAGQAPQwAAAIALwA+DAAAAQAAAAYABwjsGgIAANACBzkMAAADAGMAOwwAAAMAYQA6DAAAAwBKADwMAAACAD8AMgwAAAIAZAA9DAAAAgAvAD4MAAABAAAALAAECoEWAAIGAAgI7SXzAABlAwAGAAgI7SXzAABlAwAAAA==.Thicknzappy:BAEBLAAECoEYAAMNAAgI5R0XDACNAgg5DAAAAwBfADsMAAADAF8AOgwAAAMAOgA8DAAAAwBbADIMAAADAFEAPQwAAAMAWQA+DAAAAwAzAD8MAAADAC8ADQAICOUdFwwAjQIIOQwAAAMAXwA7DAAAAwBfADoMAAADADoAPAwAAAMAWwAyDAAAAwBRAD0MAAADAFkAPgwAAAMAMwA/DAAAAgAvAAIAAQiWBWV7AC0AAT8MAAABAA4AASwABRQHCBAABgDsGgA=.',Ti='Tinaturner:BAEALAAFFAEIAQAAAA==.',Tr='Treet:BAEALAAECgYIDQAAAA==.',Tu='Tushytantrum:BAECLAAFFIEFAAINAAMIoB6+AQAuAQM7DAAAAgBbADoMAAACAFoAPAwAAAEANQANAAMIoB6+AQAuAQM7DAAAAgBbADoMAAACAFoAPAwAAAEANQAsAAQKgRgAAg0ACAgcJV0BAGsDAA0ACAgcJV0BAGsDAAAA.',Um='Umbrachimera:BAEALAAECgMIBQAAAA==.',Un='Undiës:BAEALAAECggIDgAAAA==.Untimelydoom:BAEALAADCgcIEgAAAA==.',Va='Varcane:BAEALAAECgcIEwAAAA==.Varfotm:BAEALAADCgcIBwABLAAECgcIEwAHAAAAAA==.',Vi='Vinedragöön:BAEBLAAECoEWAAMMAAcIkxSSGADGAQc5DAAABABMADsMAAAEAD8AOgwAAAQAQAA8DAAAAwA1ADIMAAADACwAPQwAAAMAOQA+DAAAAQAIAAwABwhrE5IYAMYBBzkMAAAEAEwAOwwAAAQAPwA6DAAABABAADwMAAADADUAMgwAAAIAGAA9DAAAAwA5AD4MAAABAAgAFQABCJARHRIAMwABMgwAAAEALAAAAA==.',Vo='Voidcubus:BAEALAADCggIDwABLAAECgQIBgAHAAAAAA==.',['Vÿ']='Vÿr:BAEBLAAECoEYAAISAAgI5SDdBwDSAgg5DAAAAwBhADsMAAADAFIAOgwAAAMARwA8DAAAAwA+ADIMAAADAFUAPQwAAAMAXAA+DAAAAwBeAD8MAAADAFcAEgAICOUg3QcA0gIIOQwAAAMAYQA7DAAAAwBSADoMAAADAEcAPAwAAAMAPgAyDAAAAwBVAD0MAAADAFwAPgwAAAMAXgA/DAAAAwBXAAAA.',Wa='Warbeandk:BAEALAAECgEIAQABLAAFFAMIBQAfAJkUAA==.Warrbean:BAECLAAFFIEFAAIfAAMImRTvAgAPAQM5DAAAAgBJADsMAAABAB4AOgwAAAIANgAfAAMImRTvAgAPAQM5DAAAAgBJADsMAAABAB4AOgwAAAIANgAsAAQKgRcAAh8ACAh8Iz8EAC4DAB8ACAh8Iz8EAC4DAAAA.',Wi='Wiggledh:BAEALAAECggIEAAAAA==.',Xa='Xalatathqt:BAEALAAECgYIDQABLAAFFAMIBQANACMgAA==.',Xy='Xylla:BAEALAAECggIDAAAAA==.Xyllaphone:BAEALAAECgQIBAABLAAECggIDAAHAAAAAA==.Xyllashm:BAEALAAECgUIBQABLAAECggIDAAHAAAAAA==.',Yu='Yuzukì:BAEALAAECgUIBQAAAA==.',Za='Zapski:BAEALAAECgMIAwAAAA==.',Zo='Zoracledh:BAEALAADCggICAABLAAFFAMIBQAUAHETAA==.Zoraclefu:BAECLAAFFIEFAAIUAAMIcRNhAQD/AAM5DAAAAgA5ADsMAAABACYAOgwAAAIANQAUAAMIcRNhAQD/AAM5DAAAAgA5ADsMAAABACYAOgwAAAIANQAsAAQKgRcAAhQACAh+IXMDAO4CABQACAh+IXMDAO4CAAAA.',},}; provider.parse = parse;if ArchonTooltip.AddProviderV2 then ArchonTooltip.AddProviderV2(lookup, provider) end